grails-app/domain/dnowak_grails_assessemnt/NetAlarm.groovy
package dnowak_grails_assessemnt

import org.springframework.security.core.Authentication
import org.springframework.security.core.context.SecurityContextHolder

import java.time.*

import static dnowak_grails_assessemnt.User.currentUser

class NetAlarm {

    static belongsTo = [networkElement: NetworkElement]
    String alarmStatus
    Ticket ticket
    Boolean active = (alarmStatus==AlarmStatus.CLEARED ? false : true)
    String createdByUser = SecurityContextHolder.getContext().getAuthentication()!=null ? SecurityContextHolder.getContext().getAuthentication().getName(): null
    final LocalDateTime timestamp = LocalDateTime.now()
    String createdAt =  timestamp.toString()


    static hasOne = [ticket: Ticket]

    /*String toString(){
       String isActive = active ? "Active": "Not Active"
       def status = " ${networkElement.networkName}" + " - " + "${alarmStatus}" +" - "+ isActive
        return status
    }*/

    static constraints = {
        networkElement nullable: false, validator: { val, obj -> if (obj.networkElement.networkType == NetworkType.CARRIER) return false   }
        alarmStatus unique: true, inList:  [AlarmStatus.MINOR.toString(), AlarmStatus.CRITICAL.toString(), AlarmStatus.WARNING.toString(), AlarmStatus.CLEARED.toString()]
        active display : false
        ticket nullable: true
        createdByUser nullable:true
        timestamp  display:false
    }
}

grails-app/controllers/dnowak_grails_assessemnt/NetAlarmController.groovy
package dnowak_grails_assessemnt

import grails.plugin.springsecurity.SpringSecurityService
import org.springframework.security.core.Authentication
import org.springframework.security.core.context.SecurityContextHolder
import grails.validation.ValidationException

import javax.swing.Spring

import static org.springframework.http.HttpStatus.*

class NetAlarmController {

    def securityService

    NetAlarmService netAlarmService

   // static scaffold = NetAlarm
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond netAlarmService.list(params), model:[netAlarmCount: netAlarmService.count()]
    }

    def show(Long id) {

        respond netAlarmService.get(id)
    }

    def create() {
        respond new NetAlarm(params)
    }

    def save(NetAlarm netAlarm) {
        if (netAlarm == null) {
            notFound()
            return
        }

        try {
            netAlarmService.save(netAlarm)
        } catch (ValidationException e) {
            respond netAlarm.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'netAlarm.label', default: 'NetAlarm'), netAlarm.id])
                redirect netAlarm
            }
            '*' { respond netAlarm, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond netAlarmService.get(id)
    }

    def update(NetAlarm netAlarm) {


        if (netAlarm == null) {
            notFound()
            return
        }

        try {
            netAlarmService.save(netAlarm)
        } catch (ValidationException e) {
            respond netAlarm.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'netAlarm.label', default: 'NetAlarm'), netAlarm.id])
                redirect netAlarm
            }
            '*'{ respond netAlarm, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        netAlarmService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'netAlarm.label', default: 'NetAlarm'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'netAlarm.label', default: 'NetAlarm'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/netAlarm/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'netAlarm.label', default: 'NetAlarm')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-netAlarm" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-netAlarm" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.netAlarm}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.netAlarm}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.netAlarm}" method="POST">
                <fieldset class="form">
                    <f:field bean="netAlarm" property="networkElement"/>
                    <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <f:field bean="netAlarm" property="alarmStatus"/>
                    </sec:ifAnyGranted>
                    <sec:ifNotGranted roles="ROLE_ADMIN">
                        <g:select name="alarmStatus" value="${netAlarmInstance?.alarmStatus}" from = "['CRITICAL','MINOR', 'WARNING']" noSelection="${['null':'Select Alarm Status...']}"></g:select>
                    </sec:ifNotGranted>
                    %{--<f:all bean="netAlarm"/>--}%
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/netAlarm/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'netAlarm.label', default: 'NetAlarm')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-netAlarm" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-netAlarm" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.netAlarm}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.netAlarm}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.netAlarm}" method="PUT">
                <g:hiddenField name="version" value="${this.netAlarm?.version}" />
                <fieldset class="form">
                    <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <f:field bean="netAlarm" property="alarmStatus"/>
                    </sec:ifAnyGranted>
                    <sec:ifNotGranted roles="ROLE_ADMIN">
                        <g:select name="alarmStatus" value="${netAlarmInstance?.alarmStatus}" from = "['CRITICAL','MINOR', 'WARNING']" noSelection="${['null':'Select Alarm Status...']}"></g:select>
                    </sec:ifNotGranted>
                    %{--<f:all bean="netAlarm"/>--}%
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/netAlarm/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'netAlarm.label', default: 'NetAlarm')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-netAlarm" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-netAlarm" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${netAlarmList}" />

            <div class="pagination">
                <g:paginate total="${netAlarmCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/netAlarm/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'netAlarm.label', default: 'NetAlarm')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-netAlarm" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-netAlarm" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="netAlarm" />
            <g:form resource="${this.netAlarm}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.netAlarm}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </sec:ifAnyGranted>
                    </fieldset>
            </g:form>
        </div>
    </body>
</html>