grails-app/domain/dnowak_grails_assessemnt/NetworkElement.groovy
package dnowak_grails_assessemnt

import javax.persistence.CascadeType
import javax.persistence.FetchType
import javax.persistence.OneToMany


class NetworkElement {

    static belongsTo = [parent : NetworkElement]
    final Date createdAt = new Date()
    NetworkType networkType
    String networkName
    String identifier

    String toString(){ return ("Idenfier: "+"${identifier}" + " - " + "${networkName}") }

    //@OneToMany(fetch = FetchType.EAGER, mappedBy = "parent", cascade = CascadeType.ALL)
    static hasMany = [children : NetworkElement, alarms : NetAlarm ]

    static mapping = {

        children lazy: false
        alarms lazy: false
    }

    static constraints = {

        networkType nullable: false, inList: NetworkType.values() as List, validator: { type, networkElement ->

            if (type == NetworkType.CARRIER && networkElement.parent!=null)
            {
                return false
            }
            else if(type == NetworkType.HUB && networkElement.parent && networkElement.parent.networkType != NetworkType.CARRIER )
            {
                return false
            }
            else if(type == NetworkType.NODE && networkElement.parent.networkType != NetworkType.HUB)
            {
                return false
            }
            else if (type == NetworkType.COMPONENT && !(networkElement.parent.networkType == NetworkType.NODE  || networkElement.parent.networkType == NetworkType.COMPONENT) )
            {
                return false
            }
            else
                return true

        }
        identifier unique: true, blank: false,  nullable: false
        networkName  blank: false, validator: {val, obj, errors ->

            if(obj.id==null && obj.networkType==NetworkType.CARRIER)
            {
               if( NetworkElement.any())
                       {
                          def networkCarrierWithName  = NetworkElement.findByNetworkName(val)
                           if(networkCarrierWithName)
                               return errors.rejectValue('networkName', "${obj.getNetworkType()}" +": " + val + " already exists")
                       }
            }

             if(obj.id == null && obj.networkType != NetworkType.CARRIER && obj.parent && obj.parent.children && obj.parent.children.size() > 0 )
             {
                def allKidsElements = obj.parent.children
                def allKidsNames = allKidsElements.networkName
                if (allKidsNames.contains(val))
                {
                    return errors.rejectValue('networkName', "${obj.getNetworkType()}" + ": " + val + " already exists")
                }
            }
        }

        parent nullable: true, validator: {val, obj ->
            if (obj && obj.id==null && obj.networkType == NetworkType.CARRIER && val==null) return true
            else if (obj && obj.networkType != NetworkType.CARRIER && val==null) return false

        }
        children nullable: true
        alarms nullable: true, validator: {val, obj -> if(obj && obj.id==null&&obj.networkType == NetworkType.CARRIER && val!=null)return false }


    }
}

grails-app/controllers/dnowak_grails_assessemnt/NetworkElementController.groovy
package dnowak_grails_assessemnt

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class NetworkElementController {



    NetworkElementService networkElementService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond networkElementService.list(params), model:[networkElementCount: networkElementService.count()]
    }

    def show(Long id) {
        respond networkElementService.get(id)
    }

    def create() {
        respond new NetworkElement(params)
    }

    def save(NetworkElement networkElement) {

        if (networkElement == null) {
            notFound()
            return
        }

        try {
            networkElementService.save(networkElement)
        } catch (ValidationException e) {
            respond networkElement.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'networkElement.label', default: 'NetworkElement'), networkElement.id])
                redirect networkElement
            }
            '*' { respond networkElement, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond networkElementService.get(id)
    }

    def update(NetworkElement networkElement) {
        if (networkElement == null) {
            notFound()
            return
        }

        try {
            networkElementService.save(networkElement)
        } catch (ValidationException e) {
            respond networkElement.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'networkElement.label', default: 'NetworkElement'), networkElement.id])
                redirect networkElement
            }
            '*'{ respond networkElement, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        networkElementService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'networkElement.label', default: 'NetworkElement'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'networkElement.label', default: 'NetworkElement'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/networkElement/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'networkElement.label', default: 'NetworkElement')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-networkElement" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-networkElement" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.networkElement}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.networkElement}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.networkElement}" method="POST">
                <fieldset class="form">
                    <f:all bean="networkElement"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/networkElement/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'networkElement.label', default: 'NetworkElement')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-networkElement" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-networkElement" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.networkElement}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.networkElement}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.networkElement}" method="PUT">
                <g:hiddenField name="version" value="${this.networkElement?.version}" />
                <fieldset class="form">
                    %{--<f:all bean="networkElement"/>--}%
                    <f:field bean="networkElement" property="networkType"/>
                    <f:field bean="networkElement" property="networkName"/>
                    <f:field bean="networkElement" property="identifier"/>
                    <f:field bean="networkElement" property="parent"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/networkElement/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'networkElement.label', default: 'NetworkElement')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-networkElement" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-networkElement" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${networkElementList}" />

            <div class="pagination">
                <g:paginate total="${networkElementCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/networkElement/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'networkElement.label', default: 'NetworkElement')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-networkElement" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-networkElement" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="networkElement" />
            <g:form resource="${this.networkElement}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.networkElement}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>